<a href="https://colab.research.google.com/github/ropardo/Introducing-Python/blob/master/2_Pytorch_Basics_Math_Fundamentals/PyTorch_Basices_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.	Pytorch Basics and Math Fundamentals (Part 1)



*   2.1 Tensor and Vector
*   2.2 Tensor and Matrix
*   2.3 Dot Product
*   2.4 Softmax




In [2]:
import torch
import platform
import sys

# Check if CUDA is available
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")

if cuda_available:
    # Get CUDA version
    cuda_version = torch.version.cuda
    print(f"CUDA Version: {cuda_version}")

    # Check number of GPUs
    gpu_count = torch.cuda.device_count()
    print(f"Number of GPUs: {gpu_count}")

    # Get GPU details
    for i in range(gpu_count):
        gpu_name = torch.cuda.get_device_name(i)
        print(f"GPU {i}: {gpu_name}")
else:
    print("CUDA is not available. Ensure a GPU and CUDA toolkit are properly installed.")

# Get PyTorch version
pytorch_version = torch.__version__
print(f"PyTorch Version: {pytorch_version}")

# Get Python version
python_version = sys.version
print(f"Python Version: {python_version}")

# Check if a tensor can be moved to the GPU
if cuda_available:
    try:
        test_tensor = torch.tensor([1.0, 2.0, 3.0], device="cuda")
        print("Tensor successfully moved to GPU.")
    except Exception as e:
        print(f"Failed to move tensor to GPU: {e}")
else:
    print("No GPU available to test tensor movement.")

CUDA Available: True
CUDA Version: 12.1
Number of GPUs: 1
GPU 0: Tesla T4
PyTorch Version: 2.5.1+cu121
Python Version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Tensor successfully moved to GPU.


In [4]:
import torch
import torch.nn as nn

## 2.1	Tensor and Vector

In [5]:
vector = torch.tensor([2., 3., 4.])
print("Vector:", vector)

Vector: tensor([2., 3., 4.])


In [6]:
torch.norm(vector)

tensor(5.3852)

In [7]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-52, -57, -62, -65, -49,  90])

In [8]:
empty = torch.empty(3)
empty

tensor([4.7851e+22, 2.8826e+32, 4.4248e+30])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
arange = torch.arange(start=0, end=5, step=1)
arange

tensor([0, 1, 2, 3, 4])

In [16]:
linspace = torch.linspace(3, 10, steps=5)     # no deberia llamarse step
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [22]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace


# torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

## 2.2	Tensor and Matrix

In [23]:
A = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
A

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [3., 4., 5., 6.]])

In [24]:
zeros = torch.zeros(3, 4)
print("zeros =", zeros)

ones = torch.ones(3, 4)
print("ones =", ones)

zeros = tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [25]:
empty = torch.empty(2, 3)
print("empty =", empty)

empty = tensor([[9.1169e-30, 3.3159e-41, 9.1210e-30],
        [3.3159e-41, 1.5196e-33, 3.3159e-41]])


In [26]:
I = torch.eye(4)
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [27]:
lower_tri = torch.tril(torch.ones(5, 5))
lower_tri

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [28]:
upper_tri = torch.triu(torch.ones(5, 5))
upper_tri

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [29]:
a = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
empty_like = torch.empty_like(a)
empty_like

tensor([[ 9.0435e-30,  3.3159e-41,  9.0309e-30,  3.3159e-41],
        [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [-1.6371e+06,  3.3152e-41,  0.0000e+00,  0.0000e+00]])

In [31]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])  # means 10% chance to get a 0, and 90% chance to get a 1.
samples = torch.multinomial(probabilities, num_samples=100, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1])


In [32]:
# concatenate two tensors
A=torch.ones(2, 3)
B=2*torch.ones(4, 3)
C=torch.cat((A,B),dim=0)
print("A= ", A)
print("B =", B)
print("C =", C)

A=  tensor([[1., 1., 1.],
        [1., 1., 1.]])
B = tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
C = tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [33]:
a = torch.tensor([1, 3, 5, 8])
b = torch.tensor([2, 6, 7, 9])
c = torch.tensor([5, 6, 3, 2])
stacked = torch.stack([a, b, c], dim=0)
stacked

tensor([[1, 3, 5, 8],
        [2, 6, 7, 9],
        [5, 6, 3, 2]])

In [34]:
from torch.nn.utils.rnn import pad_sequence
a = torch.tensor([1, 3, 5, 8])
b = torch.tensor([2, 7, 9])
c = torch.tensor([5, 2])
padded = pad_sequence([a, b, c], batch_first=True)
padded

tensor([[1, 3, 5, 8],
        [2, 7, 9, 0],
        [5, 2, 0, 0]])

In [ ]:
padding_mask = padded.eq(0)
padding_mask

tensor([[False, False, False, False],
        [False, False, False,  True],
        [False, False,  True,  True]])

In [ ]:
A = torch.tensor([[1., 2., 3., 4.],
                  [2., 3., 4., 5.],
                  [3., 4., 5., 6.]])
A_T = A.transpose(-2, -1)
A_T

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])

In [ ]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10., 10.])
linear = nn.Linear(4, 3, bias=True)
print(linear(sample))

tensor([-6.9280,  4.7998, -0.2741], grad_fn=<ViewBackward0>)


## 2.3 Dot Product

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
dot_product = torch.dot(a, b)
dot_product

tensor(32)

In [ ]:
print("Dot Product:", dot_product.item())

Dot Product: 32


In [ ]:
a = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
b = torch.tensor([[7,   8,  9],
                  [10, 11, 12]])
# print( a @ b )
print(torch.matmul(a, b))


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## 2.4 Softmax

In [ ]:
logits = torch.tensor([2.0, 5.0, 3.0])
softmax = nn.functional.softmax(logits, dim=0)
print("Logits:", logits)
print("Softmax:", softmax)

Logits: tensor([2., 5., 3.])
Softmax: tensor([0.0420, 0.8438, 0.1142])


In [ ]:
a = torch.tensor([0., float('-inf')])
torch.exp(a)

tensor([1., 0.])

In [ ]:
A = torch.zeros(5, 5)
mask = torch.tril(torch.ones(5, 5))
print("mask=\n", mask)
A = A.masked_fill(mask==0, float('-inf'))
print("A=\n", A)

mask=
 tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
A=
 tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [ ]:
nn.functional.softmax(A, dim=1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])